# Generated by Django 4.2.7 on 2023-12-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(0, '0 estrella'), (1, '1 estrella'), (2, '2 estrella'), (3, '3 estrella'), (4, '4 estrella'), (5, '5 estrella')], default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_valoracion', models.DateField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaapp.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
