# Generated by Django 4.2.8 on 2023-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0002_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
